### ISSUE TITLE
docs : add Christopher Van Dyke to Contributers.md

### ISSUE THREAD

**Issue by cdvandyk-ca** [frankfarsi/onboarding-minesweeper-game#21]
I will be adding my name to the Contributers.md

**Comment by frankfarsi** [comment]
I created a branch for you

**Comment by frankfarsi** [comment]
you can clone the branch with git clone 21-van-dyke-to-contributersmd

**Comment by cdvandyk-ca** [comment]
When I try to "git push origin 21-van-dyke-to-contributersmd" I get "remote: Permission to frankfarsi/onboarding-minesweeper-game.git denied to cdvandyk-ca."

**Comment by frankfarsi** [comment]
could I see a screen shot of the error? git now only allows pushing via ssh, so I might have to show those steps too

**Comment by frankfarsi** [comment]
I saw your slack message Ive added u as a contributer see if pushing works now
